; Auto-generated. Do not edit!


(cl:in-package ped-msg)


;//! \htmlinclude msgFeedback.msg.html

(cl:defclass <msgFeedback> (roslisp-msg-protocol:ros-message)
  ((feedback
    :reader feedback
    :initarg :feedback
    :type cl:string
    :initform ""))
)

(cl:defclass msgFeedback (<msgFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <msgFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'msgFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name ped-msg:<msgFeedback> is deprecated: use ped-msg:msgFeedback instead.")))

(cl:ensure-generic-function 'feedback-val :lambda-list '(m))
(cl:defmethod feedback-val ((m <msgFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader ped-msg:feedback-val is deprecated.  Use ped-msg:feedback instead.")
  (feedback m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <msgFeedback>) ostream)
  "Serializes a message object of type '<msgFeedback>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'feedback))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'feedback))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <msgFeedback>) istream)
  "Deserializes a message object of type '<msgFeedback>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'feedback) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'feedback) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<msgFeedback>)))
  "Returns string type for a message object of type '<msgFeedback>"
  "ped/msgFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'msgFeedback)))
  "Returns string type for a message object of type 'msgFeedback"
  "ped/msgFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<msgFeedback>)))
  "Returns md5sum for a message object of type '<msgFeedback>"
  "c14cdf907e5c7c7fd47292add15660f0")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'msgFeedback)))
  "Returns md5sum for a message object of type 'msgFeedback"
  "c14cdf907e5c7c7fd47292add15660f0")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<msgFeedback>)))
  "Returns full string definition for message of type '<msgFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%string feedback~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'msgFeedback)))
  "Returns full string definition for message of type 'msgFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%string feedback~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <msgFeedback>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'feedback))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <msgFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'msgFeedback
    (cl:cons ':feedback (feedback msg))
))
