; Auto-generated. Do not edit!


(cl:in-package ped-msg)


;//! \htmlinclude msgGoal.msg.html

(cl:defclass <msgGoal> (roslisp-msg-protocol:ros-message)
  ((goal
    :reader goal
    :initarg :goal
    :type cl:string
    :initform ""))
)

(cl:defclass msgGoal (<msgGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <msgGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'msgGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name ped-msg:<msgGoal> is deprecated: use ped-msg:msgGoal instead.")))

(cl:ensure-generic-function 'goal-val :lambda-list '(m))
(cl:defmethod goal-val ((m <msgGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader ped-msg:goal-val is deprecated.  Use ped-msg:goal instead.")
  (goal m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <msgGoal>) ostream)
  "Serializes a message object of type '<msgGoal>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'goal))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'goal))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <msgGoal>) istream)
  "Deserializes a message object of type '<msgGoal>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'goal) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'goal) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<msgGoal>)))
  "Returns string type for a message object of type '<msgGoal>"
  "ped/msgGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'msgGoal)))
  "Returns string type for a message object of type 'msgGoal"
  "ped/msgGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<msgGoal>)))
  "Returns md5sum for a message object of type '<msgGoal>"
  "6e8c62b390dd09eb60220ad7325cbdf7")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'msgGoal)))
  "Returns md5sum for a message object of type 'msgGoal"
  "6e8c62b390dd09eb60220ad7325cbdf7")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<msgGoal>)))
  "Returns full string definition for message of type '<msgGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%string goal~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'msgGoal)))
  "Returns full string definition for message of type 'msgGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%string goal~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <msgGoal>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'goal))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <msgGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'msgGoal
    (cl:cons ':goal (goal msg))
))
