// Generated by gencpp from file ped/msgGoal.msg
// DO NOT EDIT!


#ifndef PED_MESSAGE_MSGGOAL_H
#define PED_MESSAGE_MSGGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ped
{
template <class ContainerAllocator>
struct msgGoal_
{
  typedef msgGoal_<ContainerAllocator> Type;

  msgGoal_()
    : goal()  {
    }
  msgGoal_(const ContainerAllocator& _alloc)
    : goal(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _goal_type;
  _goal_type goal;





  typedef boost::shared_ptr< ::ped::msgGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ped::msgGoal_<ContainerAllocator> const> ConstPtr;

}; // struct msgGoal_

typedef ::ped::msgGoal_<std::allocator<void> > msgGoal;

typedef boost::shared_ptr< ::ped::msgGoal > msgGoalPtr;
typedef boost::shared_ptr< ::ped::msgGoal const> msgGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ped::msgGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ped::msgGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ped::msgGoal_<ContainerAllocator1> & lhs, const ::ped::msgGoal_<ContainerAllocator2> & rhs)
{
  return lhs.goal == rhs.goal;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ped::msgGoal_<ContainerAllocator1> & lhs, const ::ped::msgGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ped

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ped::msgGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ped::msgGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ped::msgGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ped::msgGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ped::msgGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ped::msgGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ped::msgGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6e8c62b390dd09eb60220ad7325cbdf7";
  }

  static const char* value(const ::ped::msgGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6e8c62b390dd09ebULL;
  static const uint64_t static_value2 = 0x60220ad7325cbdf7ULL;
};

template<class ContainerAllocator>
struct DataType< ::ped::msgGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ped/msgGoal";
  }

  static const char* value(const ::ped::msgGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ped::msgGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#goal definition\n"
"string goal\n"
;
  }

  static const char* value(const ::ped::msgGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ped::msgGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct msgGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ped::msgGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ped::msgGoal_<ContainerAllocator>& v)
  {
    s << indent << "goal: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PED_MESSAGE_MSGGOAL_H
