// Generated by gencpp from file ped/set_userResponse.msg
// DO NOT EDIT!


#ifndef PED_MESSAGE_SET_USERRESPONSE_H
#define PED_MESSAGE_SET_USERRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ped
{
template <class ContainerAllocator>
struct set_userResponse_
{
  typedef set_userResponse_<ContainerAllocator> Type;

  set_userResponse_()
    : ret()  {
    }
  set_userResponse_(const ContainerAllocator& _alloc)
    : ret(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _ret_type;
  _ret_type ret;





  typedef boost::shared_ptr< ::ped::set_userResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ped::set_userResponse_<ContainerAllocator> const> ConstPtr;

}; // struct set_userResponse_

typedef ::ped::set_userResponse_<std::allocator<void> > set_userResponse;

typedef boost::shared_ptr< ::ped::set_userResponse > set_userResponsePtr;
typedef boost::shared_ptr< ::ped::set_userResponse const> set_userResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ped::set_userResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ped::set_userResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ped::set_userResponse_<ContainerAllocator1> & lhs, const ::ped::set_userResponse_<ContainerAllocator2> & rhs)
{
  return lhs.ret == rhs.ret;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ped::set_userResponse_<ContainerAllocator1> & lhs, const ::ped::set_userResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ped

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ped::set_userResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ped::set_userResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ped::set_userResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ped::set_userResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ped::set_userResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ped::set_userResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ped::set_userResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c7030931189f40243cd08ed0e4c0bac7";
  }

  static const char* value(const ::ped::set_userResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc7030931189f4024ULL;
  static const uint64_t static_value2 = 0x3cd08ed0e4c0bac7ULL;
};

template<class ContainerAllocator>
struct DataType< ::ped::set_userResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ped/set_userResponse";
  }

  static const char* value(const ::ped::set_userResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ped::set_userResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string ret\n"
"\n"
;
  }

  static const char* value(const ::ped::set_userResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ped::set_userResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ret);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct set_userResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ped::set_userResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ped::set_userResponse_<ContainerAllocator>& v)
  {
    s << indent << "ret: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.ret);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PED_MESSAGE_SET_USERRESPONSE_H
