// Generated by gencpp from file ped/set_user.msg
// DO NOT EDIT!


#ifndef PED_MESSAGE_SET_USER_H
#define PED_MESSAGE_SET_USER_H

#include <ros/service_traits.h>


#include <ped/set_userRequest.h>
#include <ped/set_userResponse.h>


namespace ped
{

struct set_user
{

typedef set_userRequest Request;
typedef set_userResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct set_user
} // namespace ped


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ped::set_user > {
  static const char* value()
  {
    return "f767d19539c13d1e285b77b3522bdee4";
  }

  static const char* value(const ::ped::set_user&) { return value(); }
};

template<>
struct DataType< ::ped::set_user > {
  static const char* value()
  {
    return "ped/set_user";
  }

  static const char* value(const ::ped::set_user&) { return value(); }
};


// service_traits::MD5Sum< ::ped::set_userRequest> should match
// service_traits::MD5Sum< ::ped::set_user >
template<>
struct MD5Sum< ::ped::set_userRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ped::set_user >::value();
  }
  static const char* value(const ::ped::set_userRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ped::set_userRequest> should match
// service_traits::DataType< ::ped::set_user >
template<>
struct DataType< ::ped::set_userRequest>
{
  static const char* value()
  {
    return DataType< ::ped::set_user >::value();
  }
  static const char* value(const ::ped::set_userRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ped::set_userResponse> should match
// service_traits::MD5Sum< ::ped::set_user >
template<>
struct MD5Sum< ::ped::set_userResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ped::set_user >::value();
  }
  static const char* value(const ::ped::set_userResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ped::set_userResponse> should match
// service_traits::DataType< ::ped::set_user >
template<>
struct DataType< ::ped::set_userResponse>
{
  static const char* value()
  {
    return DataType< ::ped::set_user >::value();
  }
  static const char* value(const ::ped::set_userResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PED_MESSAGE_SET_USER_H
